name: integration

env:
  DENO_VERSION: 2.x

on:
  schedule:
    - cron: "0 7 * * 0"
  push:
    branches:
      - main
    paths:
      - "**/*.ts"
      - "**/*.lua"
      - "**/*.vim"
      - "**/deno.json"
      - "**/deno.jsonc"
      - "README.md"
      - "doc/**"
      - ".github/workflows/integration.yml"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.ts"
      - "**/*.lua"
      - "**/*.vim"
      - "**/deno.json"
      - "**/deno.jsonc"
      - "README.md"
      - "doc/**"
      - ".github/workflows/integration.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Check TypeScript, format, and lint
        run: deno check **/*.ts && deno fmt --check **/*.ts && deno lint
      - name: Check publish packages
        run: deno task test:publish
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: "./repo"
      - uses: actions/checkout@v6
        with:
          repository: "vim-denops/denops.vim"
          path: "./denops.vim"
      - uses: actions/checkout@v6
        with:
          repository: "nvim-mini/mini.nvim"
          path: "./mini.nvim"
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - uses: rhysd/action-setup-vim@v1
        with:
          version: nightly
          neovim: true
      - name: Test
        run: deno task test
        env:
          DENOPS_TEST_DENOPS_PATH: "../denops.vim"
        working-directory: ./repo
      - name: Test Lua
        run: deno task test:lua
        env:
          MINI_TEST_PATH: "../mini.nvim"
        working-directory: ./repo
